### ISSUE TITLE
Получть ПВЗ в конкретном городе региона

### ISSUE THREAD

**Issue by PankovAlxndr** [iamwildtuna/iml-sdk#1]
Здравствуйте, вопрос, наверное, больше к IML, о задам и тут

Например у нас есть г.Дмитров , Московская обл.
он принадлежит региону "МОСКВА"

чтобы получить ПВХ только Дмитрова, мне приходится делать запрос 

`$result = $imlClient->getPvzInRegion('МОСКВА');`

который возвращает огромное количество всех ПВЗшек Москвы.. (100+ штук)

сейчас я очень некрасиво по названию области это все пытаюсь как-то отсечь и опдучить только в нудном мне маленьком городке всей московской области.. иногда работает, а инога не совсем..

Есть какое-то элегантное и надежное решение такого типа задачи?

 (по СПБ аналогично, куда что в ленинской области и возвращается се ПВЗ СПБ, хотя мне надо только одного пригорода...)

**Comment by iamwildtuna** [comment]
Приветствую! Думаю, что через API никак. Я все ПВЗ от всех ТК сохраняю к себе в базу прогоняя через DaData и сохраняя разбитый адрес в базе. Все выборки ПВЗ делаю из локальной базы. Локальная база обновляется раз в сутки по изменившимся ПВЗ + отключаю для выбора закрывшиеся.
